title: "Balena CLI Tools"
description: "Strumento Bash per installare e gestire facilmente Balena CLI"
theme: jekyll-theme-architect

url: "https://Age13Programmer.github.io"
baseurl: "/Balena-CLI-Tools/"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_downloads: true
